### ISSUE TITLE
Is it possible to convert your Shaders to the Slang format?

### ISSUE THREAD

**Issue by one-piece19** [rsn8887/Sharp-Bilinear-Shaders#1]
I really love this shaders, they are perfect. But will it be possible for you convert them to the new Slang format to be used with Vulkan?. Please

**Comment by rsn8887** [comment]
I will try.

**Comment by rsn8887** [comment]
Ok it is done on my other repo: https://github.com/rsn8887/slang-shaders

I made a Pull Request so hopefully the slang versions will be merged soon:
https://github.com/libretro/slang-shaders/pull/110

**Comment by rsn8887** [comment]
Ok my PR was merged. Should be in future buildbot versions.
